application:
  database:
    database-type: POSTGRESQL
    url: jdbc:postgresql://192.168.0.151:5432/demoforimpel
    username: lemon
    password: lemon
    driver: org.postgresql.Driver
    hbm2-ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQL82Dialect

server:
  port: 2323